apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/Dockerfile",
           "--context=/workspace",
           "--destination=james65535/vcas-demo:v20"]
    volumeMounts:
      - name: workspace-vol
        mountPath: /workspace
      - name:  registry-creds
        mountPath: /root/
  initContainers:
  - name: git-pull-init
    image: alpine/git:latest
    args: ["clone","https://github.com/james65535/vcas-demo.git","/workspace"]
    volumeMounts:
    - name: workspace-vol
      mountPath: /workspace
  volumes:
  - name: registry-creds
    projected:
      sources:
      - secret:
          name: docker-secret
          items:
          - key: .dockerconfigjson
            path: .docker/config.json
  - name: workspace-vol
    emptyDir: {}
